# Generated by Django 3.2.9 on 2021-11-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posts',
        ),
    ]
